[project]
name = "my-first-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Georg2005", email = "grigoriev.georgiy01@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
my-first-project = "my_first_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.165.10",
    "pre-commit>=4.6.2",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
